# Generated by Django 5.2.10 on 2026-02-02 05:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('location', models.CharField(default='Montréal, QC', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('set_code', models.CharField(max_length=10)),
                ('set_name', models.CharField(max_length=100)),
                ('collector_number', models.CharField(max_length=10)),
                ('rarity', models.CharField(choices=[('common', 'Commune'), ('uncommon', 'Peu commune'), ('rare', 'Rare'), ('mythic', 'Mythique')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('is_tracked', models.BooleanField(db_index=True, default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'set_code'], name='cards_card_name_df2ed1_idx'), models.Index(fields=['is_tracked', '-added_at'], name='cards_card_is_trac_7c4573_idx')],
                'unique_together': {('name', 'set_code', 'collector_number')},
            },
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=20)),
                ('language', models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Français'), ('JP', 'Japonais'), ('ES', 'Espagnol'), ('DE', 'Allemand')], default='EN', max_length=10)),
                ('foil', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cards.card')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cards.store')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['card', 'store', '-scraped_at'], name='cards_cardp_card_id_0ce0f5_idx'), models.Index(fields=['card', '-scraped_at'], name='cards_cardp_card_id_991896_idx'), models.Index(fields=['store', '-scraped_at'], name='cards_cardp_store_i_f62186_idx')],
            },
        ),
    ]
