# Generated by Django 5.2.10 on 2026-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name', 'set_code', 'collector_number'], 'verbose_name': 'Carte', 'verbose_name_plural': 'Cartes'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Magasin', 'verbose_name_plural': 'Magasins'},
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_is_trac_7c4573_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardprice',
            name='cards_cardp_card_id_991896_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardprice',
            name='cards_cardp_store_i_f62186_idx',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='collector_number',
            field=models.CharField(help_text='Numéro de collectionneur (identifie la version spécifique)', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image de la carte"),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_tracked',
            field=models.BooleanField(default=True, help_text='Si True, cette carte sera scrapée automatiquement'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'Commune'), ('uncommon', 'Peu commune'), ('rare', 'Rare'), ('mythic', 'Mythique rare'), ('special', 'Spéciale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(help_text='ID unique Scryfall (UUID)', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_code',
            field=models.CharField(help_text="Code de l'extension (ex: SNC, DMU, NEO)", max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_name',
            field=models.CharField(help_text="Nom complet de l'extension", max_length=100),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='condition',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', help_text='État de la carte', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Dollar canadien'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='CAD', max_length=3),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='foil',
            field=models.BooleanField(default=False, help_text='True si la carte est foil'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='language',
            field=models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Français'), ('PHY', 'Phyrexian'), ('JP', 'Japonais'), ('DE', 'Allemand'), ('ES', 'Espagnol'), ('IT', 'Italien'), ('PT', 'Portugais'), ('RU', 'Russe'), ('KO', 'Coréen'), ('ZHS', 'Chinois simplifié'), ('ZHT', 'Chinois traditionnel')], default='EN', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix en devise locale', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantité disponible (si connue)', null=True),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure du scraping'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='url',
            field=models.URLField(help_text='URL du produit sur le site du magasin'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(default='Montréal', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['is_tracked'], name='cards_card_is_trac_5486b6_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['scryfall_id'], name='cards_card_scryfal_248054_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprice',
            index=models.Index(fields=['card', 'condition', 'foil'], name='cards_cardp_card_id_583061_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprice',
            index=models.Index(fields=['in_stock'], name='cards_cardp_in_stoc_e405e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cardprice',
            index=models.Index(fields=['-scraped_at'], name='cards_cardp_scraped_0a9667_idx'),
        ),
    ]
