# Generated by Django 5.2.10 on 2026-03-01 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprice',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure du scraping'),
        ),
    ]
