# Generated by Django 5.2.10 on 2026-03-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cardprice_scraped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(decimal_places=2, help_text='Prix minimum trouvé', max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, help_text='Prix maximum trouvé', max_digits=10)),
                ('price_avg', models.DecimalField(decimal_places=2, help_text='Prix moyen', max_digits=10)),
                ('stores_count', models.IntegerField(default=0, help_text='Nombre de magasins avec ce prix')),
                ('in_stock_count', models.IntegerField(default=0, help_text='Nombre de magasins en stock')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Date du scraping')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cards.card')),
            ],
            options={
                'verbose_name': 'Historique Prix',
                'verbose_name_plural': 'Historiques Prix',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['card', '-scraped_at'], name='cards_price_card_id_5114e6_idx'), models.Index(fields=['-scraped_at'], name='cards_price_scraped_4ef4bd_idx')],
                'unique_together': {('card', 'scraped_at')},
            },
        ),
    ]
