# Generated by Django 5.2.10 on 2026-03-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('closed', 'Closed (Actif)'), ('open', 'Open (Paused)'), ('half_open', 'Half-Open (Testing)')], default='closed', max_length=20)),
                ('error_count', models.IntegerField(default=0, help_text="Nombre d'erreurs consécutives")),
                ('error_threshold', models.IntegerField(default=5, help_text='Seuil avant OPEN')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=300, help_text='Secondes avant HALF_OPEN (5 min par défaut)')),
                ('total_errors', models.IntegerField(default=0, help_text="Total d'erreurs historiques")),
                ('recovered_count', models.IntegerField(default=0, help_text='Nombre de fois récupéré')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_breaker', to='cards.store')),
            ],
            options={
                'verbose_name': 'Circuit Breaker',
                'verbose_name_plural': 'Circuit Breakers',
            },
        ),
    ]
