# Generated by Django 5.2.10 on 2026-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_storecircuitbreaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Nom de la tâche Celery (ex: cards.tasks.import_card_task)', max_length=255)),
                ('task_id', models.CharField(help_text='ID unique de la tâche Celery', max_length=255, unique=True)),
                ('task_args', models.JSONField(blank=True, default=list, help_text='Arguments positionnels de la tâche')),
                ('task_kwargs', models.JSONField(blank=True, default=dict, help_text='Arguments nommés de la tâche')),
                ('error_type', models.CharField(help_text="Type d'erreur (TIMEOUT, RATE_LIMITED, UNKNOWN, etc.)", max_length=100)),
                ('error_message', models.TextField(help_text="Message d'erreur complet")),
                ('traceback', models.TextField(blank=True, help_text='Stack trace complète')),
                ('attempt_count', models.IntegerField(default=1, help_text='Nombre de tentatives effectuées')),
                ('max_retries', models.IntegerField(default=3, help_text='Nombre maximum de retries configuré')),
                ('is_retryable', models.BooleanField(default=True, help_text='True si la tâche peut être retentée manuellement')),
                ('is_resolved', models.BooleanField(default=False, help_text='True si la tâche a été résolue/retentée avec succès')),
                ('failed_at', models.DateTimeField(auto_now_add=True, help_text='Date de la défaillance')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date de la résolution (si applicable)', null=True)),
            ],
            options={
                'verbose_name': 'Tâche Failée',
                'verbose_name_plural': 'Tâches Failées',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['task_name', '-failed_at'], name='cards_taskf_task_na_3a3293_idx'), models.Index(fields=['error_type', '-failed_at'], name='cards_taskf_error_t_77d98a_idx'), models.Index(fields=['-failed_at'], name='cards_taskf_failed__1863ee_idx'), models.Index(fields=['is_resolved'], name='cards_taskf_is_reso_31e102_idx')],
            },
        ),
    ]
